/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum CreditCardType {
  Unset = 0,
  Visa = 1,
  MasterCard = 2,
  AmericanExpress = 3,
  Discover = 4,
  DinersClub = 5,
  Jcb = 6,
  AustralianBankCard = 7
}
export declare function maskCreditCard(input: string): string
export declare function classifyCreditCard(input: string): boolean
